### ISSUE TITLE
Kubernetes Lite

### ISSUE THREAD

**Issue by spjmurray** [unikorn-cloud/kubernetes#186]
Following on from https://github.com/unikorn-cloud/region/issues/103...

We have lots of Kubernetes regions, now we need to make it multi-tenant.  Enter vCluster, this needs to:

* Allow ingress creation to support hosted services
* Turn on the limit ranger to add pod resource requests 
* Turn on the quotas to constrain users
  * amount of CPU/memory
  * number of GPUs
  * number of load balancers (control over IP exhaustion)
* Network isolation
* Integrate with the metrics server for example for performance monitoring, other integrations are possible e.g. cert-manager but we don't want an upgrade to affect everyone probably!
* Be usable e.g. have DNS, have an ingress (combine with cert-manager and external-dns for this)

Pretty trivial so far, that will define what knobs we have to tweak, then we need to expose this as a super simplified API without all the workload pool nonsense.

**Comment by yankcrime** [comment]
We'll still need an option of defining workload pools somehow, as an example when a user needs dedicated baremetal nodes as part of their cluster as well as additional capacity for non-GPU workloads.  We also might want to consider pools of a particular node type for a certain classes of workload and how they could be defined when a user creates their cluster.

**Comment by spjmurray** [comment]
@yankcrime 's point is handled in this separate issue: https://github.com/unikorn-cloud/kubernetes/issues/187

**Comment by spjmurray** [comment]
For reference I've tested a very early cut using the following configuration

```yaml
controlPlane:
  ingress:
    enabled: true
    host: uks-lite-d717c48f.staging.unikorn-cloud.org
    annotations:
      external-dns.alpha.kubernetes.io/hostname: uks-lite-d717c48f.staging.unikorn-cloud.org
  # PRO only :/
  #hostPathMapper:
  #  enabled: true
  backingStore:
    database:
      embedded:
        enabled: true
  statefulSet:
    persistence:
      volumeClaim:
        retentionPolicy: Delete
integrations:
  metricsServer:
    enabled: true
    nodes: false
policies:
  resourceQuota:
    enabled: true
  limitRange:
    enabled: true
  networkPolicy:
    enabled: true
exportKubeConfig:
  server: https://uks-lite-d717c48f.staging.unikorn-cloud.org
```

That gives us DNS/SNI based routing.  The snag here is that as the virtual cluster uses mTLS for auth, we cannot terminate TLS at the ingress and have to allow pass-through.  This is a separate option that needs to be enabled on ingress-nginx.

To enable the metrics server to work, you will also need:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: unikorn-metrics-server
spec:
  podSelector:
    matchLabels:
      release: uks-lite-d717c48f
  egress:
    - ports:
      - port: 443
    - to:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: metrics-server
  policyTypes:
    - Egress
```

to be applied in the vCluster namespace.
