### ISSUE TITLE
AMD GPU Operator rollout fails to initialise GPUs

### ISSUE THREAD

**Issue by yankcrime** [unikorn-cloud/kubernetes#214]
When an AMD GPU is detected we deploy the GPU Operator from [this fork](https://github.com/spjmurray/gpu-operator).  The branch we're deploying from has a value of `latest` for the KMM worker images ([set in the KMM sub-chart](https://github.com/ROCm/gpu-operator/blob/d6fc1dbfe6b10d10704a187d2ff839932d69d3da/helm-charts-k8s/charts/kmm/values.yaml#L13)) and the referenced image tag here doesn't exist.  The upshot is that GPUs aren't initialised correctly when a `DeviceConfig` is created.

Either the values in the chart need amending (which is what upstream does on release), or we need to set this in the ArgoCD application definition:

```
       - name: kmm.controller.manager.env.relatedImageWorker
         value: docker.io/rocm/kernel-module-management-worker:v1.2.0
```

The corollary to this is that we should also be creating the `DeviceConfig` automatically so that when we create a cluster, the Operator is informed of which driver it should use.  An example `DeviceConfig` looks like this:

```yaml
apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: nscale-rocm-64
  namespace: kube-system
spec:
  driver:
    enable: true
    blacklist: true
    image: docker.io/nscaledev/amdgpu-driver
    version: "6.4"

  devicePlugin:
    devicePluginImage: rocm/k8s-device-plugin:latest
    nodeLabellerImage: rocm/k8s-device-plugin:labeller-latest

  metricsExporter:
     enable: false
     serviceType: "NodePort"
     nodePort: 32500
     image: rocm/device-metrics-exporter:v1.0.0

  selector:
    feature.node.kubernetes.io/amd-gpu: "true"
```

The driver selection rule logic by the Operator is documented here: https://instinct.docs.amd.com/projects/gpu-operator/en/latest/drivers/precompiled-driver.html#how-kmm-selects-driver-images

Since the driver should be loaded from a container image, we'll need to ensure the right combination of ROCm version and  Linux kernel are available in images we build.
